language: node_js
dist: xenial

node_js:
  - '8'
  - '10'
  - '12'
  - 'node'

services:
  - mongodb
  - mysql
  - postgresql

cache:
  yarn: true
  directories:
    - 'node_modules'

script:
  - yarn lint
  - ORM_PARALLEL=1 ORM_PORT=3306 yarn coverage

before_install:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
  - yarn config set ignore-engines true

before_script:
  - mysql -u root -e 'CREATE DATABASE mikro_orm_test;'
  - psql -c 'CREATE DATABASE mikro_orm_test;' -U postgres

after_success:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
  - yarn coveralls
