version: "3.4"

services:
  # mongodb is managed via `run-rs`

  mysql:
    container_name: mysql
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql

  mariadb:
    image: mariadb:10.4
    ports:
      - 3309:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mariadb:/var/lib/mysql

  postgre:
    container_name: postgre
    image: postgres:11.7
    ports:
      - 5432:5432
    volumes:
      - postgre:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  mysql:
  mariadb:
  postgre:
