version: "3.4"

services:
  # mongodb is managed via `run-rs`

  mysql:
    image: mysql:5.7
    restart: unless-stopped
    ports:
      - 3307:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mysql:/var/lib/mysql

  mariadb:
    image: mariadb:10.5
    ports:
      - 3309:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mariadb:/var/lib/mysql

  postgre:
    image: postgres:12.3
    ports:
      - 5432:5432
    volumes:
      - postgre:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  mysql:
  mariadb:
  postgre:
