services:
  mongo:
    image: mongo:8.0
    expose:
      - 27017
    ports:
      - "27017:27017"
    restart: always

  mysql8:
    image: mysql:8.3-oracle
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command: [
      "mysqld",
      "--default-authentication-plugin=mysql_native_password",
      "--innodb_file_per_table=0",
      "--innodb_doublewrite=0",
      "--skip-name-resolve"
    ]
    volumes:
      - mysql8:/var/lib/mysql

  mariadb:
    image: mariadb:11
    ports:
      - "3309:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mariadb:/var/lib/mysql

  postgre:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    volumes:
      - postgre:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  postgis:
    image: imresamu/postgis:16-3.4
    ports:
      - "5433:5432"
    volumes:
      - postgis:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  mssql:
    image: mcr.microsoft.com/azure-sql-edge:latest
    ports:
      - "1433:1433"
    cap_add:
      - SYS_PTRACE
    environment:
      MSSQL_SA_PASSWORD: Root.Root
      MSSQL_TELEMETRY_ENABLED: 0
      ACCEPT_EULA: 1

volumes:
  mysql8:
    driver_opts:
      type: tmpfs
      device: tmpfs
  mariadb:
    driver_opts:
      type: tmpfs
      device: tmpfs
  postgre:
    driver_opts:
      type: tmpfs
      device: tmpfs
  postgis:
    driver_opts:
      type: tmpfs
      device: tmpfs
