services:
  mongo:
    image: mongo:8.0
    expose:
      - 27017
    ports:
      - "27017:27017"
    restart: always

  mysql9:
    image: mysql:9.0-oracle
    restart: unless-stopped
    ports:
      - "3308:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command: [
      "mysqld",
      "--innodb_file_per_table=0",
      "--innodb_doublewrite=0",
      "--skip-name-resolve"
    ]
    volumes:
      - mysql9:/var/lib/mysql

  mariadb:
    image: mariadb:11
    ports:
      - "3309:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - mariadb:/var/lib/mysql

  postgre:
    image: pgvector/pgvector:pg16
    ports:
      - "5432:5432"
    volumes:
      - postgre:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  postgis:
    image: imresamu/postgis:16-3.4
    ports:
      - "5433:5432"
    volumes:
      - postgis:/var/lib/postgresql/data
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust

  mssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    restart: always
    ports:
      - '1433:1433'
    environment:
      MSSQL_SA_PASSWORD: Root.Root
      MSSQL_TELEMETRY_ENABLED: 0
      ACCEPT_EULA: 1
    healthcheck:
      test: /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P 'Root.Root' -Q 'select 1'

  waitmssql:
    image: mcr.microsoft.com/mssql/server:2025-latest
    links:
      - mssql
    depends_on:
      - mssql
    environment:
      MSSQL_PID: Express
    entrypoint:
      - bash
      - -c
      # https://docs.microsoft.com/en-us/sql/relational-databases/logs/control-transaction-durability?view=sql-server-ver15#bkmk_DbControl
      - 'until /opt/mssql-tools/bin/sqlcmd -S mssql -U sa -P Root.Root -d master -Q ""; do sleep 5; done'

volumes:
  mysql9:
    driver_opts:
      type: tmpfs
      device: tmpfs
  mariadb:
    driver_opts:
      type: tmpfs
      device: tmpfs
  postgre:
    driver_opts:
      type: tmpfs
      device: tmpfs
  postgis:
    driver_opts:
      type: tmpfs
      device: tmpfs
